### ISSUE TITLE
[o11y] Add base alert rules to all CKF charms with metrics

### ISSUE THREAD

**Issue by rgildein** [canonical/bundle-kubeflow#1026]
### Context

Add base alert rules (from KF093 spec) to all charms with metrics implementation.

```yaml
groups:
- name: <charm-name>
  rules:
  - alert: KubeflowServiceDown
    expr: up{} < 1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.juju_charm }} service is Down ({{ $labels.juju_model }}/{{ $labels.juju_unit }})"
      description: |
       One or more targets of {{ $labels.juju_charm }} charm are down on unit {{ $labels.juju_model }}/{{ $labels.juju_unit }}.
       LABELS = {{ $labels }}

  - alert: KubeflowServiceIsNotStable
    expr: avg_over_time(up{}[10m]) < 0.5
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "{{ $labels.juju_charm }} service is not stable ({{ $labels.juju_model }}/{{ $labels.juju_unit }})"
      description: |
        {{ $labels.juju_charm }} unit {{ $labels.juju_model }}/{{ $labels.juju_unit }} has been unreachable at least 50% of the time over the last 10 minutes.
        LABELS = {{ $labels }}
```

### What needs to get done

1.  Add KubeflowServiceDown and KubeflowServiceIsNotStable alert rules to charms
2. They tested their presence with [`assert_alert_rules`](https://github.com/canonical/charmed-kubeflow-chisme/blob/b64f6ccca228d08c6533cbe83382306cd46670dc/src/charmed_kubeflow_chisme/testing/cos_integration.py#L413).

### Definition of Done

1. Alerts are present in each charm
2. These changes are backported to 1.9.
