### ISSUE TITLE
Bundle for 1.9 is missing the branch gh metadata

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1037]
### Bug Description

This was found while working on https://github.com/canonical/bundle-kubeflow/issues/1036

The previous bundles for 1.8 had `_github_repo_branch` metadata keys in the bundle, in order for the scanning scripts to gather the images from the corresponding branches.
https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.8/stable/kubeflow/bundle.yaml#L11

But for 1.9 everything is set to `main`. This means that all scripts now are going to be using the `tools/get-images.sh` scripts from the `main` branches of the charms

### To Reproduce

Run the image gathering script from airgap for the 1.9 bundle. It will end up showing images from the `main` branches

### Environment

Current `main` 
https://github.com/canonical/bundle-kubeflow/tree/b2269189231aea9a1c594def3bd92549ebb3ee0d

### Relevant Log Output

```yaml
bundle: kubernetes
name: kubeflow
docs: https://discourse.charmhub.io/t/3749
applications:
  admission-webhook:
    charm: admission-webhook
    channel: 1.9/stable
    trust: true
    scale: 1
    _github_repo_name: admission-webhook-operator
    _github_repo_branch: main
  argo-controller:
    charm: argo-controller
    channel: 3.4/stable
    trust: true
    scale: 1
    _github_repo_name: argo-operators
    _github_repo_branch: main
...
```
