### ISSUE TITLE
kfp and mlflow UATs fail intermittently when run using the driver with poddefaults not applied to Job Pod

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#1066]
### Bug Description

UATs that utilize kfp and mlflow components fail intermittently in Azure one-click deployment when run using the driver. The following UATs were seen to fail:

- e2e-wine-kfp-mlflow-kserve
- kfp-v1-integration
- kfp-v2-integration
- kserve-integration
- mlflow-integration
- mlflow-kserve
- mlflow-minio-integration

The logs from the failure are:
```
E           ApiException: (401)
E           Reason: Unauthorized
E           HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Wed, 04 Sep 2024 11:52:49 GMT', 'content-length': '827', 'x-envoy-upstream-service-time': '4', 'server': 'envoy'})
E           HTTP response body: {"error":"List v1beta1 experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","code":16,"message":"List v1beta1 experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","details":[{"@type":"type.googleapis.com/google.rpc.Status","code":16,"message":"Failed to check authorization. User identity is empty in the request header"}]}
```
Note: These logs are the same as we've seen in #951, so at first glance we assumed it's the same issue. After some debugging in https://github.com/canonical/bundle-kubeflow/issues/951#issuecomment-2331211702 and https://github.com/canonical/bundle-kubeflow/issues/951#issuecomment-2343498647, we concluded it's a different issue and created this one.

All the above failing UATs require some PodDefaults to be created in the user namespace, in this case the one created by the driver `test-kubeflow`.
When checking the namespace for the PodDefaults, they are found there:
```
kubectl get poddefaults -n test-kubeflow
NAME                         AGE
access-ml-pipeline           18s
mlflow-server-access-minio   19s
mlflow-server-minio          20s
```
however, when checking the pod created by the job, it is not mutated as indicated by the poddefaults, i.e. the following is not found in the [pod yaml](https://pastebin.canonical.com/p/xqXCXc8j7F/):
* `volume-kf-pipeline-token` volume and volumeMount
* `KF_PIPELINES_SA_TOKEN_PATH` env
* `AWS_ACCESS_KEY_ID` env
* `AWS_SECRET_ACCESS_KEY` env
* `MINIO_ENDPOINT_URL` env
* `MLFLOW_S3_ENDPOINT_URL` env
* `MLFLOW_TRACKING_URI` env

`admission-webhook` charm is responsible for applying these PodDefaults, the logs from `admission-webhook` container are in [this pastebin](https://pastebin.canonical.com/p/Kj5nJDVftz/). (Note: In this pastebin, the admission webhook image is slightly modified for more verbose logs, but it's the exact same as the one used in the charm except for log verbosity)

Notice in the `admission-webhook` container logs:
```
fetched 0 poddefault(s) in namespace test-kubeflow
```

### To Reproduce

run the UATs in one-click deployment [using the driver](https://github.com/canonical/charmed-kubeflow-uats?tab=readme-ov-file#running-from-a-configured-management-environment-using-the-driver)

### Environment

AKS 1.29.7
juju 3.6-beta2

### Relevant Log Output

[job pod yaml](https://pastebin.canonical.com/p/xqXCXc8j7F/)
[admission webhook logs](https://pastebin.canonical.com/p/Kj5nJDVftz/)
[UATs run logs](https://pastebin.canonical.com/p/KVMJTqjFRR/)

**Comment by NohaIhab** [comment]
After some debugging, we observed the following behaviors:
* no poddefaults applied to the pod
* only mlflow poddefault was applied to the pod and not kfp

We can deduce that happens is a race condition between the poddefaults being created and the job's pod being created in the tests. The failing sequence of events is:
1. profile is created -> namespace is created
2. job is created -> request to create the pod is sent -> request goes by admission webhook but it does not find poddefaults in the namespace so no mutating takes place and pod gets created without the volume and envs.
3. poddefaults are created in the namespace

**Comment by NohaIhab** [comment]
The UATs are passing when running from a Notebook with the poddefaults selected, or manually creating the job by:
1. create the Profile with the yaml:
```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: test-kubeflow
spec:
  owner:
    kind: User
    name: test-kubeflow@email.com
```
2. wait a few seconds,
3. create the Job manually with the yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2024-09-11T11:03:16Z"
  generation: 1
  labels:
    access-minio: "true"
    access-ml-pipeline: "true"
    job-name: test-kubeflow
    mlflow-server-minio: "true"
  name: test-kubeflow
  namespace: test-kubeflow
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        access-minio: "true"
        access-ml-pipeline: "true"
        job-name: test-kubeflow
        mlflow-server-minio: "true"
    spec:
      containers:
      - args:
        - |
          cd /tests/charmed-kubeflow-uats/tests;
          pip install -r requirements.txt >/dev/null;
          pytest;
          # Kill Istio Sidecar after workload completes to have the Job status properly updated
          # https://github.com/istio/istio/issues/6324
          x=$(echo $?);
          curl -fsI -X POST http://localhost:15020/quitquitquit >/dev/null && exit $x;
        command:
        - bash
        - -c
        image: kubeflownotebookswg/jupyter-scipy:v1.9.0
        imagePullPolicy: IfNotPresent
        name: test-kubeflow
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tests
          name: test-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --repo=https://github.com/canonical/charmed-kubeflow-uats
        - --ref=27d985656b96bab53034f95c1cd28f8abe66aac9
        - --root=/tests
        - --group-write
        - --one-time
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        imagePullPolicy: IfNotPresent
        name: git-sync
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tests
          name: test-volume
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
      serviceAccount: default-editor
      serviceAccountName: default-editor
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: test-volume
```
This confirms that it is indeed a race condition between the poddefaults being created and the job's pod being created.
To fix the issue, we can add a check to the driver that the poddefaults are in the namespace before creating the job.
