### ISSUE TITLE
Scheduled AKS and EKS ci doesn't work due to empty version 

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#1119]
### Bug Description

When scheduled, the workflows do not work because they are given an empty [bundle_version](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L40). 

When [scheduled](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L15), there are no inputs (as when run from a workflow_dispatch). IIUC, this results in the workflow to [call](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L33) the [parse_versions.py](https://github.com/canonical/bundle-kubeflow/blob/main/scripts/gh-actions/parse_versions.py) script with an input `""`. The script expects no argument in order to fail, thus it doesn't fail and instead outputs [bundle_versions=[""]](https://github.com/canonical/charmed-kubeflow-solutions/actions/runs/11364182718/job/31609681521?pr=7#step:5:13). 

We need to refactor the preprocess script/job in order to account for cases without inputs. 

### To Reproduce

trigger without any inputs e.g. `pull_request` event or wait for scheduled action

### Environment

GH runners

### Relevant Log Output

```shell
n/a
```

**Comment by orfeas-k** [comment]
I see this was a design pattern in https://github.com/canonical/bundle-kubeflow/pull/1101

> the default value in the parse_versions() function has been removed, so calling the script without any arguments raises an appropriate exception.

This however is not in sync with our expected scheduled behaviour, where we want to run the workflows for latest + the two supported versions.

**Comment by orfeas-k** [comment]
After a quick sync with @mvlassis, we both agreed that default values should only be set in the workflow and not the script. With that in mind, we came up with the two options:
1. Adding a step in preprocess input job, that will run only on schedule and then this will be passed to the script as an argument, when `input.kf_version` is empty:
  ```
      - name: Set env
        if: ${{ github.event_name == 'schedule' }}
        run: echo "BUNDLE_VERSION=1.9" >> $GITHUB_ENV
          
      - name: Process bundle versions
        id: process_bundle_versions
        run: python scripts/gh-actions/parse_versions.py "${{ inputs.bundle_version || env.BUNDLE_VERSION }}"
 ```
2. Modify the workflows to enable `workflow_call` with the same inputs that `workflow_dispatch` has and then create a separate e.g. `deploy-to-eks-schedule.yaml` or `scheduled.yaml` workflow that will call the `deploy-to-a/eks.yaml` with the appropriate inputs (setting the default there).

**Comment by DnPlas** [comment]
I'm not sure I'd like to go with (2), it seems to be adding more maintenance to us. I think I prefer going with a hybrid of (1), but first, I think there are a couple things going on here:

1. The python script is not raising when expected. I have noticed that the lines checking the length of the "input" is slightly incorrect. Right now we are doing the following in [L15-L16](https://github.com/canonical/bundle-kubeflow/blob/05f3f1ae2317bf1a7378725a35681be2187304c8/scripts/gh-actions/parse_versions.py#L15C1-L16C62):

```python
    if len(sys.argv) < 1: # <--- this will always be True, as sys.argv[0] is always the name of the script
        raise Exception("No bundle versions given as input.")
```
In a `pdb` session:

```bash
$ python3 scripts/gh-actions/parse_versions.py ""
-> if len(sys.argv) < 1:
(Pdb) sys.argv
['scripts/gh-actions/parse_versions.py', '']
(Pdb) len(sys.argv)
2
(Pdb) sys.argv[0]
'scripts/gh-actions/parse_versions.py'
```

We have to change this to either `sys.argv[1]` or, slightly fancier, refactor with `argparse`.

2. Since the `${{ inputs.bundle_version }}` will be null for the scheduled workflow run, we don't need to run anything from the [preprocess input job](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L18C3-L18C19) on schedule. 

#### Proposal

I think we can:

* Set an `if` in the `preprocess-input` job to run only on workflow dispatch. We have to make sure this won't run on schedule, otherwise (according to the preprocess script) it will raise, causing the job to fail.
* Create another job called `generate-bundle-versions` that generates the bundle versions based on the condition that the wf is run on schedule or wf dispatch.
* Use `dependencies.yaml` to parse the bundle versions on schedule

So it would look like:

```yaml
# please be mindful the syntax can be slightly wrong

jobs:
  preprocess-input:
  if: ${{ github.event_name == 'wf dispatch' }} # we should check the actual name
  ...

  generate-bundle-versions-on-sched:
  if: ${{ github.event_name == 'schedule' }}
  run: |
    bundle_versions=$(yq -j '. | keys' dependencies.yaml) # this gives you a json array
    echo "bundle_versions=$" >> "$GITHUB_OUTPUT"

  deploy-ckf-to-aks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        bundle_version: ${{ fromJSON(jobs.preprocess-input.outputs.processed_bundle_versions) || fromJSON(jobs.generate-bundle-versions-on-sched.outputs.bundle_versions) }}
```

thoughts?
