### ISSUE TITLE
Describe how the Velero charm should update its status

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1226]
### Context

Needed for our spec https://github.com/canonical/bundle-kubeflow/issues/1222

The Velero charm will need to have a logic for settings its status depending on the state of Velero in the cluster. We'll need to expose:
1. How should the charm detect the Velero state?
    1. What K8s objects should it look at?
3. What are the different potential statuses that the charm could go into

### What needs to get done

1. Describe all the Velero K8s resources that are created during installation
2. Document their expected statuses
3. Describe scenarios in which the Velero installation is considered broken

### Definition of Done

1. Document the above in our spec

**Comment by Deezzir** [comment]
## Update 

### Components

**NOTE**: The following list of objects is created when the `velero install` command is run with `--use-node-agent` and AWS provider/plugin. For example:

```bash
velero install \                                                                                      
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.10.0 \
    --bucket velero \
    --use-node-agent \
    --secret-file ./credentials-velero \
    --backup-location-config region=us-east2 \
    --snapshot-location-config region=us-east2 \
```

During the installation, the Velero deployed the following objects (in order):

1. `Namespace` (the first step is the namespace creation) which has `velero` namespace by default(it can be overridden).
```yaml
apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    labels:
      component: velero
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/audit-version: latest
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/enforce-version: latest
      pod-security.kubernetes.io/warn: privileged
      pod-security.kubernetes.io/warn-version: latest
    name: velero
  spec: {}
```
2. `CluterRoleBinding` - grants the Velero service account cluster-wide administrative privileges by binding it to the cluster-admin `ClusterRole`. This allows the Velero service account to perform any action on any resource across all namespaces.
``` yaml
apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
```
3. `ServiceAccount` - is used by the Velero backup and restore system to authenticate and perform actions within the cluster.
```yaml
apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
```
4. `Secret` - provides AWS S3 bucket access credentials for the backup/restore remote location.
```yaml
apiVersion: v1
  data:
    cloud: <hidden>
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: cloud-credentials
    namespace: velero
  type: Opaque
```
5. `BackupStorageLocation` - is CRD created by Velero to configure the location and provider used to store K8s objects for backup/restore functionality.
```yaml
apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: default
    namespace: velero
  spec:
    config:
      region: us-east2
    default: true
    objectStorage:
      bucket: velero
    provider: aws
```
6. `VolumeSnapshotLocation` is a CRD created by Velero to configure the location and provider used to store volume snapshots for backup/restore functionality (the location and provider can differ from the backup storage).
```yaml
apiVersion: velero.io/v1
  kind: VolumeSnapshotLocation
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: default
    namespace: velero
  spec:
    config:
      region: us-east2
    provider: aws
```
7. `Deployment` - the main component of the Velero server deployment.
```yaml
apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
  spec:
    selector:
      matchLabels:
        deploy: velero
    strategy: {}
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8085"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          component: velero
          deploy: velero
      spec:
        containers:
        - args:
          - server
          - --features=
          - --uploader-type=kopia
          command:
          - /velero
          env:
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LD_LIBRARY_PATH
            value: /plugins
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.15.2
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: metrics
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        initContainers:
        - image: velero/velero-plugin-for-aws:v1.10.0
          imagePullPolicy: IfNotPresent
          name: velero-velero-plugin-for-aws
          resources: {}
          volumeMounts:
          - mountPath: /target
            name: plugins
        restartPolicy: Always
        serviceAccountName: velero
        volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
```

- **Observation 1**: Velero pods expose the `/metrics` endpoint for Prometheus metrics, which we can leverage in the future for observability. [Here](https://pastebin.canonical.com/p/C8PvDVnFhD/) is the exported metrics example. (See `annotations` and `containerPort`).
- **Observation 2**: Velero uses the `velero server` command in the pods, acting like the Velero server side. The same binary is used for the client side to interact with the Velero Restore/Backup controllers(served by the pods).
- **Observation 3**:  The plugins passed to the `velero install` command are deployed as an `initContainer` within the Velero pods. The server uses those containers to talk to the cloud providers and create backups/restores.

8. `DaemonSet` is deployed because the `--use-node-agent` flag was provided; it allows Velero to back up the PV and PVCs from all the nodes in the cluster. I assume that Velero uses the following architecture:
    1. Velero Server (Deployment)
        Manages overall backup and restore operations.
        Coordinates backup scheduling and metadata storage.
    2. Velero Node-Agent (DaemonSet)
       Runs on each node.
       Handles volume snapshots and storage interactions.
       Ensures data is copied from the node to the backup storage.

```yaml
apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: node-agent
    namespace: velero
  spec:
    selector:
      matchLabels:
        name: node-agent
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: velero
          name: node-agent
      spec:
        containers:
        - args:
          - node-agent
          - server
          - --features=
          command:
          - /velero
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.15.2
          imagePullPolicy: IfNotPresent
          name: node-agent
          ports:
          - containerPort: 8085
            name: metrics
          resources: {}
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /host_pods
            mountPropagation: HostToContainer
            name: host-pods
          - mountPath: /var/lib/kubelet/plugins
            mountPropagation: HostToContainer
            name: host-plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        securityContext:
          runAsUser: 0
        serviceAccountName: velero
        volumes:
        - hostPath:
            path: /var/lib/kubelet/pods
          name: host-pods
        - hostPath:
            path: /var/lib/kubelet/plugins
          name: host-plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
    updateStrategy: {}
kind: List
```

### Statuses

The only objects whose statuses we must consider are `Deployment` and `DaemonSet` (if deployed).

- `Deployment` must have the `Available` condition set to `True`. *Note*: We must ensure the deployment has been available for at least 10 seconds. This is because the deployment can show as Ready momentarily before the pods fall into a `CrashLoopBackOff`.
- `DaemonSet`  must have the number of ready and running pods equal to the number of pods that should be scheduled. For example, ' numberAvailable = desiredNumberScheduled`.

Taking into account the findings above, I can consider the Velero deployment "broken" if the following conditions are not met:
- Any objects described above are not present on the cluster(in the Velero namespace).
- `Deployment` and/or `DaemonSet` are not in the "ready" state.
- Velero is not publishing Prometheus metrics
