### ISSUE TITLE
Need help with EC2 cluster setup.

### ISSUE THREAD

**Issue by jcs021102** [canonical/bundle-kubeflow#1239]
when I run: `eksctl create cluster -f cluster.yaml`
```sh
Error: invalid configuration for "aws-ebs-csi-driver" addon: at most one of wellKnownPolicies, serviceAccountRoleARN, attachPolicyARNs and attachPolicy can be specified
```

Cluster.yaml:
```yaml
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- eu-central-1a
- eu-central-1b
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
addons:
- name: aws-ebs-csi-driver
  serviceAccountRoleARN: "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  wellKnownPolicies:
   ebsCSIController: true
kind: ClusterConfig
kubernetesNetworkConfig:
  ipFamily: IPv4
managedNodeGroups:
- amiFamily: Ubuntu2004
  iam:
    withAddonPolicies:
      ebs: true
  instanceType: t2.2xlarge
  labels:
    alpha.eksctl.io/cluster-name: scrumptious-wardrobe-1684842095
    alpha.eksctl.io/nodegroup-name: ng-d06bd84e
  maxSize: 2
  minSize: 2
  name: ng-d06bd84e
  releaseVersion: ""
  ssh:
    allow: true
    publicKeyName: key
  tags:
    alpha.eksctl.io/nodegroup-name: ng-d06bd84e
    alpha.eksctl.io/nodegroup-type: managed
  volumeSize: 100
metadata:
  name: kubeflow-instance
  region: eu-central-1
  version: "1.24"
```
