### ISSUE TITLE
Spec for having access to ISVCs from outside the cluster

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1240]
### Context

Right now users have no way of accessing InferenceServices that are exposed outside the cluster, when the IngressGateway is connected to AuthService.

There is a hacky way of using the session cookie from a browser, but this should not be considered for production environments.

### What needs to get done

1. Expose how to create tokens, that AuthService accepts
2. Describe the needed changes for users to be able to issue such tokens from their Notebooks

### Definition of Done

1. We have a spec that outlines the above

**Comment by kimwnasptd** [comment]
More specifically, AuthService is able to validate tokens included in the `Authorization: Bearer ${TOKEN}` header if:
1. The token is a K8s ServiceAccountToken
2. The token's `audience` includes `istio-ingressgateway.istio-system.svc.cluster.local` [[1]](https://github.com/arrikto/oidc-authservice/blob/0c4ea9aa5e962c7f946c1acb65cfae3b0f604817/common/settings.go#L30) [[2]](https://github.com/arrikto/oidc-authservice/blob/master/authenticators/jwt.go#L127)

AuthService will use the [TokenReview API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/) of K8s to validate the Token, and then ensures the audience is as expected.

This means that users can use ServiceAccountTokens with the above audience, and AuthService will allow them to pass.

**Comment by kimwnasptd** [comment]
A use-case for users to be able to use such tokens is the following:
1. Users should be able to create ServiceAccountTokens (need specific audience)
2. `default-editor` ServiceAccount, used by Notebooks, need to have necessary RBAC to create such tokens
3. Users create ServiceAccountTokens with specific expiration date and audiences to use from outside the cluster

## Demo
This can be done with the following:
```yaml
# permissions.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: kubeflow-tokens-edit
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
```

The above ClusterRole can be deployed automatically via the kubeflow-roles-operator https://github.com/canonical/kubeflow-roles-operator/issues/113, so that all `default-editor` ServiceAccounts get the permissions out of the box.

Then, users can create tokens the following way:
```bash
export TOKEN=$(kubectl create token \
    default-editor \
    --duration=600s \
    --audience=istio-ingressgateway.istio-system.svc.cluster.local)
echo $TOKEN
```

Lastly, the token can be used from outside the cluster, to hit an ISVC for example
```bash
export ISVC_URL=$(kubectl get isvc \
    sklearn-iris \
    -o jsonpath='{.status.address.url}')
echo $ISVC_URL

curl $ISVC_URL/v1/models/sklearn-iris:predict \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Content-Type: application/json' \
    -d @./iris-input.json
```
