### ISSUE TITLE
Katib on Kubeflow on MicroK8s

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#336]
Following this [discussion](https://kubeflow.slack.com/archives/C7REE0EHK/p1615727756022200), a user was having issues on using Katib with MicroK8s.

"Anytime I try to run an experiment, it created an experiment but no trials, suggestion and hyperparameter tuning occurs. "

cc @DomFleischmann @knkski

**Comment by Josepholaidepetro** [comment]
This is the katib YAML file @RFMVasconcelos @knkski @DomFleischmann :

```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  name: mavencode
  namespace: kubeflow-josepholaide10
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parameters:
    - name: --learning-rate
      parameterType: double
      feasibleSpace:
        min: "0.2"
        max: "0.5"
    - name: --momentum
      parameterType: double
      feasibleSpace:
        min: "0.5"
        max: "0.8"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 2
              restartPolicy: OnFailure
              template:
                metadata:
                  annotations:
                    sidecar.istio.io/inject: "false"
                spec:
                  containers:
                    - name: tensorflow
                      # modify this property if you would like to use a custom image
                      image: mavencodev/katib:2.0
                      imagePullPolicy: Always
                      command: ["python", "-u", "/mnist.py"]
                      args:
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}"
                        - "{{.Value}}"
                        {{- end}}
                        {{- end}}

```
