### ISSUE TITLE
Kubeflow dashboard: Cannot load dashboard menu link

### ISSUE THREAD

**Issue by olokshyn** [canonical/bundle-kubeflow#344]
/kind bug

**What steps did you take and what happened**:
1. On a fresh Ubuntu 20.04.02 LTS virtual machine
2. Installed kubeflow using microk8s by following [these instructions](https://ubuntu.com/tutorials/deploy-kubeflow-ubuntu-windows-mac#3-install-microk8s):

```
sudo snap install microk8s --channel 1.20/stable --classic
sudo microk8s status --wait-ready
sudo usermod -a -G microk8s $USER
sudo chown -f -R $USER ~/.kube
microk8s.enable dns dashboard storage
microk8s.enable kubeflow
```
and it reported that the kubeflow is ready
3. Logged into the dashboard successfully (not from the first attempt though, there were several 404s but it fixed itself)
4. The dashboard was missing essential links to Jupyter Notebooks and Pipelines, sample pipelines were also missing and the error "Cannot load dashboard menu link" was displayed, as shown on the screenshots below:
![image](https://user-images.githubusercontent.com/17240466/116195452-e82ae880-a73a-11eb-95aa-b7306c21b3c2.png)
![image](https://user-images.githubusercontent.com/17240466/116195555-0abd0180-a73b-11eb-873f-2d253af0145f.png)

**What did you expect to happen**:
1. Jupyter Notebook and Pipelines links are present on the dashboard.
2. No errors shown.

**Suspects**:
The `configmaps/centraldashboard-config` config map is missing in the deployment.

**Investigation**:
1. As seen in the browser console, the `/api/dashboard-links` URI returns 500 error.
2. I have the following virtual services in the kubeflow namespace:

```
$ microk8s.kubectl -n kubeflow get vs
NAME                 GATEWAYS                        HOSTS   AGE
argo-ui              ["kubeflow/kubeflow-gateway"]   ["*"]   26h
dex-auth             ["kubeflow/kubeflow-gateway"]   ["*"]   26h
jupyter-web          ["kubeflow/kubeflow-gateway"]   ["*"]   26h
kubeflow-dashboard   ["kubeflow/kubeflow-gateway"]   ["*"]   26h
pipelines-api        ["kubeflow/kubeflow-gateway"]   ["*"]   26h
pipelines-viewer     ["kubeflow/kubeflow-gateway"]   ["*"]   26h
katib-ui             ["kubeflow/kubeflow-gateway"]   ["*"]   26h
metadata-ui          ["kubeflow/kubeflow-gateway"]   ["*"]   26h
oidc-gatekeeper      ["kubeflow/kubeflow-gateway"]   ["*"]   26h
pipelines-ui         ["kubeflow/kubeflow-gateway"]   ["*"]   26h
```

3. The route `/api/dashboard-links` is supposed to be matched to the kubeflow-dashboard virtualservice and sent to the kubeflow-dashboard ClusterIP service:

```
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: kubeflow-dashboard.kubeflow.svc.cluster.local
        port:
          number: 8082
```

4. The kubeflow-dashboard service says it was not able to get a ConfigMap:

```
$ microk8s.kubectl -n kubeflow logs -f -l juju-app=kubeflow-dashboard -c kubeflow-dashboard
Unable to fetch ConfigMap: {
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'configmaps "centraldashboard-config" not found',
  reason: 'NotFound',
  details: { name: 'centraldashboard-config', kind: 'configmaps' },
  code: 404
}
```

5. The `centraldashboard-config` is indeed missing in the deployment:

```
$ microk8s.kubectl -n kubeflow get configmaps centraldashboard-config
Error from server (NotFound): configmaps "centraldashboard-config" not found
```

```
$ microk8s.kubectl get configmaps --all-namespaces | grep centraldashboard-config
$ # Nothing here!
```
6. Another 500 error in the browser console comes from the `/pipeline/apis/v1betra1/pipelines` URL managed by the pipelines-api virtualservice:

```
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /apis/v1beta1/pipelines
    rewrite:
      uri: /apis/v1beta1/pipelines
    route:
    - destination:
        host: pipelines-api.kubeflow.svc.cluster.local
        port:
          number: 8888
```

7. And there it fails with en error I cannot interpret:

```
$ microk8s.kubectl -n kubeflow logs -l juju-app=pipelines-api -c pipelines-api
github.com/kubeflow/pipelines/backend/api/go_client._PipelineService_ListPipelines_Handler
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/pipeline.pb.go:1040
google.golang.org/grpc.(*Server).processUnaryRPC
	external/org_golang_google_grpc/server.go:966
google.golang.org/grpc.(*Server).handleStream
	external/org_golang_google_grpc/server.go:1245
google.golang.org/grpc.(*Server).serveStreams.func1.1
	external/org_golang_google_grpc/server.go:685
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1333
```
