### ISSUE TITLE
[KFP] Experiment Run UI does not finish to load

### ISSUE THREAD

**Issue by phvalguima** [canonical/bundle-kubeflow#395]
Hi,

Juju provider: MAAS
Bundle: https://pastebin.canonical.com/p/njzcFzNNcv/
Running latest kubeflow from: ```juju deploy cs:kubeflow```

After creating a Run for a given Experiment + Pipeline, the UI takes me to a screen ("Run") which stays loading.

Looking into Chrome DevTools, I can see it repeats the same POST commands.
```
$ curl 'http://172.27.16.70:30771/ml_metadata.MetadataStoreService/GetContextByTypeAndName' \
   -H 'Connection: keep-alive' \
   -H 'X-User-Agent: grpc-web-javascript/0.1' \
   -H 'X-Grpc-Web: 1' \
   -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36' \
   -H 'Content-Type: application/grpc-web+proto' \
   -H 'Accept: */*' \
   -H 'Origin: http://172.27.16.70:30771' \
   -H 'Referer: http://172.27.16.70:30771/pipeline/' \
   -H 'Accept-Language: en-US,en;q=0.9' \
   -H 'Cookie: _xsrf=2|<REDACTED>; authservice_session=<REDACTED>' \
   --data-raw $'\u0000\u0000\u0000\u0000n\n\u0003run\u0012gconditional_execution_pipeline_with_exit_handler.conditional-execution-pipeline-with-exit-handler-252v7' \
   --compressed \
   --insecure
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /ml_metadata.MetadataStoreService/GetContextByTypeAndName</pre>
</body>
</html>
```

Kubeflow's Kustomize script includes a virtual service for ml_metadata, which is not deployed by default:
Kustomize: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/metadata/options/istio/virtual-service.yaml
Whereas, on a recent charm deployment, I can only see:
```
$ kubectl get virtualservices.networking.istio.io -A
NAMESPACE   NAME                 GATEWAYS                        HOSTS   AGE
kubeflow    dex-auth             ["kubeflow/kubeflow-gateway"]   ["*"]   103m
kubeflow    jupyter-ui           ["kubeflow/kubeflow-gateway"]   ["*"]   103m
kubeflow    katib-ui             ["kubeflow/kubeflow-gateway"]   ["*"]   106m
kubeflow    kfp-ui               ["kubeflow/kubeflow-gateway"]   ["*"]   103m
kubeflow    kubeflow-dashboard   ["kubeflow/kubeflow-gateway"]   ["*"]   103m
kubeflow    kubeflow-volumes     ["kubeflow/kubeflow-gateway"]   ["*"]   103m
kubeflow    oidc-gatekeeper      ["kubeflow/kubeflow-gateway"]   ["*"]   103m
```

I've applied the following virtual service:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: metadata-grpc
  namespace: kubeflow
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /ml_metadata
    rewrite:
      uri: /ml_metadata
    route:
    - destination:
        host: mlmd.kubeflow.svc.cluster.local
        port:
          number: 8080
```

And now, the CURL command above returns ```upstream connect error or disconnect/reset before headers. reset reason: remote reset``` instead.
