### ISSUE TITLE
nvidia.com/gpu: Invalid value, who is responsible for publishing kubeflow-dashboard bundle?

### ISSUE THREAD

**Issue by gcheron** [canonical/bundle-kubeflow#408]
I have the following issue:

`[422] Notebook.kubeflow.org "test2" is invalid: spec.template.spec.containers.resources.limits.nvidia.com/gpu: Invalid value: "integer": spec.template.spec.containers.resources.limits.nvidia.com/gpu in body must be of type string: "integer" http://192.168.1.30/jupyter/api/namespaces/admin/notebooks`

That has already been mentioned in https://github.com/canonical/bundle-kubeflow/issues/390

When we download `kubeflow-dashboard` from the charm store:
https://api.jujucharms.com/charmstore/v5/kubeflow-dashboard-56/archive

the content of `metadata.yaml` is:

```
name: kubeflow-dashboard
display-name: Kubeflow Central Dashboard
summary: Kubeflow Central Dashboard
description: Kubeflow Central Dashboard
maintainers: [Juju Developers <juju@lists.ubuntu.com>]
tags: [ai, bigdata, kubeflow, machine-learning, tensorflow]
series: [kubernetes]
resources:
  oci-image:
    type: oci-image
    description: 'Backing OCI image'
    auto-fetch: true
    upstream-source: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.3.0-rc.1
requires:
  ingress:
    interface: ingress
    schema: https://raw.githubusercontent.com/canonical/operator-schemas/service-mesh-schemas/ingress.yaml
    versions: [v1]
  kubeflow-profiles:
    interface: k8s-service
    schema: https://raw.githubusercontent.com/canonical/operator-schemas/master/k8s-service.yaml
    versions: [v1]
min-juju-version: 2.8.6
```

To fix the bug we just need to replace
`    upstream-source: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.3.0-rc.1`
by
`    upstream-source: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.3.1-rc.0`

as `v1.3.1-rc.0` contains the fix from [PR](https://github.com/kubeflow/kubeflow/pull/5891) related to https://github.com/kubeflow/kubeflow/issues/6014

But my question is: who is responsible for this bundle? where can we provide a PR for fixing the upstream-source?

Thanks.
