### ISSUE TITLE
Notebook cannot implicitly connect to/launch runs in the Pipelines client

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#423]
Currently in a notebook, this does not work:
```
import kfp
client = kfp.Client()
```
reporting:
```
ERROR:root:Failed to read a token from file '/var/run/secrets/kubeflow/pipelines/token' ([Errno 2] No such file or directory: '/var/run/secrets/kubeflow/pipelines/token').
WARNING:root:Failed to set up default credentials. Proceeding without credentials...
```

I think this is because, when switching to multi-user isolation for pipelines, we missed adding [this](https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/#multi-user-mode) to the `PodDefault`s for each user.  

As a temporary workaround, used can from a terminal on cluster create a PodDefault in their namespace:
```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: "<YOUR_USER_PROFILE_NAMESPACE>"
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  volumes:
    - name: volume-kf-pipeline-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: pipelines.kubeflow.org      
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/pipelines
      name: volume-kf-pipeline-token
      readOnly: true
  env:
    - name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token
```

which will then enable **new** notebook servers to select KFP access in the `Configurations` section of the new notebook page.  

Another hack that will let you use kfp from an existing notebook is to copy your session cookie from your browser's development tools, then do:
```
cookies = 'authservice_session=<your cookie from your browser>'
client = kfp.Client(
    host="http://10.64.140.43.nip.io/pipeline",
    cookies=cookies,
)
```
