### ISSUE TITLE
Having trouble persisting config map edits

### ISSUE THREAD

**Issue by choyuansu** [canonical/bundle-kubeflow#505]
I found that whenever I made changes to config maps, they seem to get reverted to the original after a few days.

Example 1: Save pipeline logs to MinIO and show logs in UI
I changed environment variable `ARGO_ARCHIVE_LOGS` in `deployment/kfp-ui` to true and changed `configmap/argo-controller-configmap-config` to look like this:
```
...
data:
  config: |
    artifactRepository:
      archiveLogs: true
      s3:
...
```
This worked for a few days before they both returned to the original settings where logs are not displayed and not saved to S3.

Example 2: Setting default image for Jupyter notebook server
I changed `configmap/jupyter-ui-config-config` to this:
```
...
    spawnerFormDefaults:
      image:
        value: my/image:latest
        options:
        - my/image:latest
...
```
It also worked for a few days before changing back to the original default images.

Based on @wallyworld's comment [here](https://discourse.charmhub.io/t/configmaps-in-k8s-charms/1220/2), Juju creates these config maps. So I assume my changes are overwritten by Juju? If so, is there a way to prevent that from happening? Or are there other ways to achieve what I want to do?
