### ISSUE TITLE
Seldon Core examples from public S3 storage behind proxy

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#550]
When trying the Seldon Core examples in the Charmed Kubeflow deployed behind the proxy they are stuck when downloading the model from public GCP or AWS object storage. Even if proxy and storage configuration is provided using the secret (same as for Minio).

Reproduce:
1. Deploy Kubeflow with proper proxy settings
2. Deploy SeldonCore model

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://seldon-models/mlflow/elasticnet_wine_1.8.0
        name: classifier
        envSecretRefName: seldon-init-container-secret
      name: default
      replicas: 1
```

**Workaround**
Copy the model to the local Minio and run the example from it.
