### ISSUE TITLE
Login redirects back to login page with OIDC integration

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#552]
**Reproduce**
1. Install Kubeflow with OIDC integration (ie. adfs)
2. Open the browser in incognito mode (because logout does not work)
3. Login using OIDC
4. Put in login / pass / mfa
5. You get redirected to <KUBEFLOW-IP>/dex/auth?client_id=authservice-oidc&redirect_uri=%2Fauthservice%2Foidc%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=<state>

**Workaround**
Select "Log in with adfs" to be redirected to Kubeflow Dashboard.

OIDC configuration:
```
- id: adfs
  name: adfs
  type: oidc
  config:
    issuer: https://<ADFS-URL>/adfs
    clientID: <client-id>
    clientSecret: <client-secret>
    redirectURI: <KUBEFLOW-URL>/dex/callback
    userNameKey: unique_name
    userIDKey: unique_name
    insecureSkipEmailVerified: true
    claimMapping:
      preferred_username: unique_name
      email: unique_name
```
