### ISSUE TITLE
In Kubeflow deployment without MLflow we cannot deploy model with Seldon from Minio

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#560]
The secret to accessing Minio for models is created only if the deployment has MLflow added.

There is a valid use case for deploying a model stored in Minio without MLflow (ie sklearn model hosting using Seldon).

**Comment by Barteus** [comment]
Workaround - manually create a secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: minio123
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: minio123
  RCLONE_CONFIG_S3_ENDPOINT: http://minio.kubeflow.svc.cluster.local:9000
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
```
