### ISSUE TITLE
Create an airgapped release of CKF 1.8

### ISSUE THREAD

**Issue by AlexanderSing** [canonical/bundle-kubeflow#818]
### Context

Recently, further scripts and tests for deploying CKF in an airgapped environment were merged and I am grateful for these contributions.
Based on them I tried deploying stable/1.8 in an airgapped manner but ran into some problems. 

1. It seems that the envoy-operator is trying to reach raw.githubusercontent.com/canonical/operator-schemas/master/grpc.yaml as part of its `set_pod_spec` call, which doesn't work in an airgapped environment
2. Not sure if thats because of my environment but using the argo-controller 398 charm, I get a missing authorization: `lightkube.core.exceptions.ApiError: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kubeflow:argo-controller" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope`

In my case, I actually currently have access to the docker.io and gcr.io container registries, that's why they are still referred to in the .yaml file. However, this will be changed later on to a hosted registry.

I used the following bundle-airgap.yaml:
```
bundle: kubernetes
name: kubeflow
applications:
  admission-webhook:
    charm: ./admission-webhook_r275.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/kubeflownotebookswg/poddefaults-webhook:v1.8.0
  dex-auth:
    charm: ./dex-auth_r358.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/dexidp/dex:v2.36.0
  istio-ingressgateway:
    charm: ./istio-gateway_r723.charm
    options:
      kind: ingress
      proxy-image: docker.io/istio/proxyv2:1.17.3
    scale: 1
    trust: true
  istio-pilot:
    charm: ./istio-pilot_r711.charm
    scale: 1
    trust: true
    options:
      default-gateway: kubeflow-gateway
      image-configuration: '{"pilot-image": "pilot", "global-tag": "1.17.3", "global-hub": "docker.io/istio", "global-proxy-image": "proxyv2", "global-proxy-init-image": "proxyv2", "grpc-bootstrap-init": "busybox:1.28"}'
  jupyter-controller:
    charm: ./jupyter-controller_r824.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/kubeflownotebookswg/notebook-controller:v1.8.0
  jupyter-ui:
    charm: ./jupyter-ui_r746.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/kubeflownotebookswg/jupyter-web-app:v1.8.0
    options:
      jupyter-images: "['docker.io/kubeflownotebookswg/jupyter-scipy:v1.8.0','docker.io//kubeflownotebookswg/jupyter-pytorch-full:v1.8.0','docker.io//kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.8.0','docker.io//kubeflownotebookswg/jupyter-tensorflow-full:v1.8.0','docker.io//kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.8.0']"
      rstudio-images: "['docker.io/kubeflownotebookswg/rstudio-tidyverse:v1.8.0']"
      vscode-images: "['docker.io/kubeflownotebookswg/codeserver-python:v1.8.0']"

  katib-db:
    charm: ./mysql-k8s_r113.charm
    scale: 1
    trust: true
    constraints: mem=2G
    resources:
      mysql-image: ghcr.io/canonical/charmed-mysql:8.0.35-22.04_edge
  katib-db-manager:
    charm: ./katib-db-manager_r411.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/kubeflowkatib/katib-db-manager:v0.16.0
  katib-ui:
    charm: ./katib-ui_r422.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/kubeflowkatib/katib-ui:v0.16.0
  kfp-api:
    charm: ./kfp-api_r1035.charm
    scale: 1
    trust: true
    resources:
      oci-image: ghcr.io/charmedkubeflow/api-server:2.0.3-e037d33
    options:
      cache-image: busybox
  kfp-db:
    charm: ./mysql-k8s_r113.charm
    scale: 1
    trust: true
    constraints: mem=2G
    resources:
      mysql-image: ghcr.io/canonical/charmed-mysql:8.0.35-22.04_edge
  kfp-metadata-writer:
    charm: ./kfp-metadata-writer_r118.charm
    scale: 1
    trust: true
    resources:
      oci-image: gcr.io/ml-pipeline/metadata-writer:2.0.3
  kfp-persistence:
    charm: ./kfp-persistence_r1039.charm
    scale: 1
    trust: true
    resources:
      oci-image: ghcr.io/charmedkubeflow/persistenceagent:2.0.3-a3714a9
  kfp-profile-controller:
    charm: ./kfp-profile-controller_r998.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/python:3.7
  kfp-schedwf:
    charm: ./kfp-schedwf_r1052.charm
    scale: 1
    trust: true
    resources:
      oci-image: ghcr.io/charmedkubeflow/scheduledworkflow:2.0.3-7d6d3e4
  kfp-ui:
    charm: ./kfp-ui_r1034.charm
    scale: 1
    trust: true
    resources:
      ml-pipeline-ui: ghcr.io/charmedkubeflow/frontend:2.0.3-d4ac42b
  kfp-viewer:
    charm: ./kfp-viewer_r1064.charm
    scale: 1
    trust: true
    resources:
      kfp-viewer-image: ghcr.io/charmedkubeflow/viewer-crd-controller:2.0.3-d89d9fc
  kfp-viz:
    charm: ./kfp-viz_r985.charm
    scale: 1
    trust: true
    resources:
      oci-image: ghcr.io/charmedkubeflow/visualization-server:2.0.3-8169d0c
  knative-eventing:
    charm: ./knative-eventing_r353.charm
    scale: 1
    trust: true
    options:
      namespace: knative-eventing
      custom_images: '{ "eventing-webhook/eventing-webhook": "gcr.io/knative-releases/knative.dev/eventing/cmd/webhook:c9c582f530155d22c01b43957ae0dba549b1cc903f77ec6cc1acb9ae9085be62", "eventing-controller/eventing-controller": "gcr.io/knative-releases/knative.dev/eventing/cmd/controller:cbc452f35842cc8a78240642adc1ebb11a4c4d7c143c8277edb49012f6cfc5d3", "mt-broker-filter/filter": "gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter:33ea8a657b974d7bf3d94c0b601a4fc287c1fb33430b3dda028a1a189e3d9526", "mt-broker-ingress/ingress": "gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress:f4a9dfce9eec5272c90a19dbdf791fffc98bc5a6649ee85cb8a29bd5145635b1", "mt-broker-controller/mt-broker-controller": "gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker:c5d3664780b394f6d3e546eb94c972965fbd9357da5e442c66455db7ca94124c", "imc-controller/controller": "gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller:3ced549336c7ccf3bb2adf23a558eb55bd1aec7be17837062d21c749dfce8ce5", "imc-dispatcher/dispatcher": "gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher:e17bbdf951868359424cd0a0465da8ef44c66ba7111292444ce555c83e280f1a", "pingsource-mt-adapter/dispatcher": "gcr.io/knative-releases/knative.dev/eventing/cmd/mtping:bc200a12cbad35bea51aabe800a365f28a5bd1dd65b3934b3db2e7e22df37efd", "migrate": "gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate:59431cf8337532edcd9a4bcd030591866cc867f13bee875d81757c960a53668d", }'
  knative-operator:
    charm: ./knative-operator_r328.charm
    scale: 1
    trust: true
    resources:
      knative-operator-image: gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.10.3
      knative-operator-webhook-image: gcr.io/knative-releases/knative.dev/operator/cmd/webhook:v1.10.3
    options:
      otel-collector-image: docker.io/otel/opentelemetry-collector:latest
  knative-serving:
    charm: ./knative-serving_r354.charm
    scale: 1
    trust: true
    options:
      namespace: knative-serving
      istio.gateway.namespace: kubeflow
      istio.gateway.name: kubeflow-gateway
      version: 1.8.0
      custom_images: '{ "activator": "gcr.io/knative-releases/knative.dev/serving/cmd/activator:c3bbf3a96920048869dcab8e133e00f59855670b8a0bbca3d72ced2f512eb5e1", "autoscaler": "gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:caae5e34b4cb311ed8551f2778cfca566a77a924a59b775bd516fa8b5e3c1d7f", "controller": "gcr.io/knative-releases/knative.dev/serving/cmd/controller:38f9557f4d61ec79cc2cdbe76da8df6c6ae5f978a50a2847c22cc61aa240da95", "webhook": "gcr.io/knative-releases/knative.dev/serving/cmd/webhook:bc13765ba4895c0fa318a065392d05d0adc0e20415c739e0aacb3f56140bf9ae", "autoscaler-hpa": "gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa:7003443f0faabbaca12249aa16b73fa171bddf350abd826dd93b06f5080a146d", "net-istio-controller/controller": "gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:2b484d982ef1a5d6ff93c46d3e45f51c2605c2e3ed766e20247d1727eb5ce918", "net-istio-webhook/webhook": "gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:59b6a46d3b55a03507c76a3afe8a4ee5f1a38f1130fd3d65c9fe57fff583fa8d", "domain-mapping": "gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping:763d648bf1edee2b4471b0e211dbc53ba2d28f92e4dae28ccd39af7185ef2c96", "domainmapping-webhook": "gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook:a4ba0076df2efaca2eed561339e21b3a4ca9d90167befd31de882bff69639470", "migrate": "gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate:d0095787bc1687e2d8180b36a66997733a52f8c49c3e7751f067813e3fb54b66", "queue-proxy": "gcr.io/knative-releases/knative.dev/serving/cmd/queue:505179c0c4892ea4a70e78bc52ac21b03cd7f1a763d2ecc78e7bbaa1ae59c86c", }'
  kserve-controller:
    charm: ./kserve-controller_r435.charm
    scale: 1
    trust: true
    options:
      deployment-mode: rawdeployment
      custom_images: '{ "configmap__agent": "docker.io/kserve/agent:v0.11.1", "configmap__batcher": "docker.io/kserve/agent:v0.11.1", "configmap__explainers__alibi": "docker.io/kserve/alibi-explainer:latest", "configmap__explainers__aix": "docker.io/kserve/aix-explainer:latest", "configmap__explainers__art": "docker.io/kserve/art-explainer:latest", "configmap__logger": "docker.io/kserve/agent:v0.11.1", "configmap__router": "docker.io/kserve/router:v0.11.1", "configmap__storageInitializer": "docker.io/kserve/storage-initializer:v0.11.1", "serving_runtimes__lgbserver": "docker.io/kserve/lgbserver:v0.11.1", "serving_runtimes__kserve_mlserver": "docker.io/seldonio/mlserver:1.3.2", "serving_runtimes__paddleserver": "docker.io/kserve/paddleserver:v0.11.1", "serving_runtimes__pmmlserver": "docker.io/kserve/pmmlserver:v0.11.1", "serving_runtimes__sklearnserver": "docker.io/kserve/sklearnserver:v0.11.1", "serving_runtimes__tensorflow_serving": "docker.io/tensorflow/serving:2.6.2", "serving_runtimes__torchserve": "docker.io/pytorch/torchserve-kfs:0.7.0", "serving_runtimes__tritonserver": "nvcr.io/nvidia/tritonserver:21.09-py3", "serving_runtimes__xgbserver": "docker.io/kserve/xgbserver:v0.11.1", }'
    resources:
      kserve-controller-image: docker.io/kserve/kserve-controller:v0.11.1
      kube-rbac-proxy-image: docker.io/kubebuilder/kube-rbac-proxy:v0.13.1
  kubeflow-dashboard:
    charm: ./kubeflow-dashboard_r454.charm
    scale: 1
    trust: true
    resources:
      oci-image: docker.io/kubeflownotebookswg/centraldashboard:v1.8.0
  kubeflow-profiles:
    charm: ./kubeflow-profiles_r355.charm
    scale: 1
    trust: true
    resources:
      profile-image: docker.io/kubeflownotebookswg/profile-controller:v1.8.0
      kfam-image: docker.io/kubeflownotebookswg/kfam:v1.8.0
  kubeflow-roles:
    charm: ./kubeflow-roles_r187.charm
    scale: 1
    trust: true
  metacontroller-operator:
    charm: ./metacontroller-operator_r226.charm
    scale: 1
    trust: true
    options:
      metacontroller-image: docker.io/metacontrollerio/metacontroller:v3.0.0
  oidc-gatekeeper:
    charm: ./oidc-gatekeeper_r294.charm
    scale: 1
    resources:
      oci-image: docker.io/kubeflowmanifestswg/oidc-authservice:e236439
  pvcviewer-operator:
    charm: ./pvcviewer-operator_r30.charm
    scale: 1
    series: focal
    trust: true
    resources:
      oci-image: docker.io/kubeflownotebookswg/pvcviewer-controller:v1.8.0
  seldon-controller-manager:
    charm: ./seldon-core_r590.charm
    scale: 1
    trust: true
    resources:
      oci-image: ghcr.io/charmedkubeflow/seldon-core-operator:1.17.1-c95840c
    options:
      custom_images: '{ "configmap__predictor__tensorflow__tensorflow": "docker.io/tensorflow/serving:2.1.0", "configmap__predictor__tensorflow__seldon": "docker.io/seldonio/tfserving-proxy:1.15.0", "configmap__predictor__sklearn__seldon": "ghcr.io/charmedkubeflow/sklearnserver:v1.16.0_20.04_1", "configmap__predictor__sklearn__v2": "ghcr.io/charmedkubeflow/mlserver-sklearn:1.2.0_22.04_1", "configmap__predictor__xgboost__seldon": "docker.io/seldonio/xgboostserver:1.15.0", "configmap__predictor__xgboost__v2": "ghcr.io/charmedkubeflow/mlserver-xgboost:1.2.0_22.04_1", "configmap__predictor__mlflow__seldon": "docker.io/seldonio/mlflowserver:1.15.0", "configmap__predictor__mlflow__v2": "ghcr.io/charmedkubeflow/mlserver-mlflow:1.2.0_22.04_1", "configmap__predictor__triton__v2": "nvcr.io/nvidia/tritonserver:21.08-py3", "configmap__predictor__huggingface__v2": "ghcr.io/charmedkubeflow/mlserver-huggingface:1.2.4_22.04_1", "configmap__predictor__tempo_server__v2": "docker.io/seldonio/mlserver:1.2.0-slim", "configmap_storageInitializer": "docker.io/seldonio/rclone-storage-initializer:1.14.1", "configmap_explainer": "docker.io/seldonio/alibiexplainer:1.15.0", "configmap_explainer_v2": "docker.io/seldonio/mlserver:1.2.0-alibi-explain", }'
      executor-container-image-and-version: docker.io/seldonio/seldon-core-executor:1.17.1
  tensorboard-controller:
    charm: ./tensorboard-controller_r257.charm
    scale: 1
    trust: true
    resources:
      tensorboard-controller-image: docker.io/kubeflownotebookswg/tensorboard-controller:v1.8.0
  tensorboards-web-app:
    charm: ./tensorboards-web-app_r245.charm
    scale: 1
    trust: true
    resources:
      tensorboards-web-app-image: docker.io/kubeflownotebookswg/tensorboards-web-app:v1.8.0
  training-operator:
    charm: ./training-operator_r330.charm
    scale: 1
    trust: true
    resources:
      training-operator-image: docker.io/kubeflow/training-operator:v1-855e096
relations:
  - [dex-auth:oidc-client, oidc-gatekeeper:oidc-client]
  - [istio-pilot:ingress, dex-auth:ingress]
  - [istio-pilot:ingress, jupyter-ui:ingress]
  - [istio-pilot:ingress, katib-ui:ingress]
  - [istio-pilot:ingress, kfp-ui:ingress]
  - [istio-pilot:ingress, kubeflow-dashboard:ingress]
  - [istio-pilot:ingress, oidc-gatekeeper:ingress]
  - [istio-pilot:ingress-auth, oidc-gatekeeper:ingress-auth]
  - [istio-pilot:istio-pilot, istio-ingressgateway:istio-pilot]
  - [istio-pilot:ingress, tensorboards-web-app:ingress]
  - [istio-pilot:gateway-info, tensorboard-controller:gateway-info]
  - [katib-db-manager:relational-db, katib-db:database]
  - [kfp-api:relational-db, kfp-db:database]
  - [kfp-api:kfp-api, kfp-persistence:kfp-api]
  - [kfp-api:kfp-api, kfp-ui:kfp-api]
  - [kfp-api:kfp-viz, kfp-viz:kfp-viz]
  - [kserve-controller:ingress-gateway, istio-pilot:gateway-info]
  - [kserve-controller:local-gateway, knative-serving:local-gateway]
  - [kubeflow-profiles, kubeflow-dashboard]
  - [kubeflow-dashboard:links, jupyter-ui:dashboard-links]
  - [kubeflow-dashboard:links, katib-ui:dashboard-links]
  - [kubeflow-dashboard:links, kfp-ui:dashboard-links]
  - [kubeflow-dashboard:links, tensorboards-web-app:dashboard-links]

```
and followed that up with the following script:
```
juju deploy ./argo-controller_r398.charm --resource oci-image=docker.io/argoproj/workflow-controller:v3.3.10 --config executor-image=docker.io/argoproj/argoexec:v3.3.10
juju deploy ./katib-controller_r446.charm --resource oci-image=docker.io/kubeflowkatib/katib-controller:v0.16.0 --config custom_images='{"default_trial_template": "docker.io/kubeflowkatib/mxnet-mnist:v0.16.0","early_stopping__medianstop": "docker.io/kubeflowkatib/earlystopping-medianstop:v0.16.0","enas_cpu_template": "docker.io/kubeflowkatib/enas-cnn-cifar10-cpu:v0.16.0","metrics_collector_sidecar__stdout": "docker.io/kubeflowkatib/file-metrics-collector:v0.16.0","metrics_collector_sidecar__file": "docker.io/kubeflowkatib/file-metrics-collector:v0.16.0","metrics_collector_sidecar__tensorflow_event": "docker.io/kubeflowkatib/tfevent-metrics-collector:v0.16.0","pytorch_job_template__master": "docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.16.0","pytorch_job_template__worker": "docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.16.0","suggestion__random": "docker.io/kubeflowkatib/suggestion-hyperopt:v0.16.0","suggestion__tpe": "docker.io/kubeflowkatib/suggestion-hyperopt:v0.16.0","suggestion__grid": "docker.io/kubeflowkatib/suggestion-optuna:v0.16.0","suggestion__hyperband": "docker.io/kubeflowkatib/suggestion-hyperband:v0.16.0","suggestion__bayesianoptimization": "docker.io/kubeflowkatib/suggestion-skopt:v0.16.0","suggestion__cmaes": "docker.io/kubeflowkatib/suggestion-goptuna:v0.16.0","suggestion__sobol": "docker.io/kubeflowkatib/suggestion-goptuna:v0.16.0","suggestion__multivariate_tpe": "docker.io/kubeflowkatib/suggestion-optuna:v0.16.0","suggestion__enas": "docker.io/kubeflowkatib/suggestion-enas:v0.16.0","suggestion__darts": "docker.io/kubeflowkatib/suggestion-darts:v0.16.0","suggestion__pbt": "docker.io/kubeflowkatib/suggestion-pbt:v0.16.0", }'
juju deploy ./kubeflow-volumes_r260.charm --resource oci-image=docker.io/kubeflownotebookswg/volumes-web-app:v1.8.0
juju deploy ./minio_r258.charm --resource oci-image=docker.io/minio/minio:RELEASE.2021-09-03T03-56-13Z
juju deploy ./mlmd_r127.charm --resource oci-image=gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
juju deploy ./envoy_r101.charm --resource oci-image=gcr.io/ml-pipeline/metadata-envoy:2.0.2


juju relate argo-controller minio
juju relate istio-pilot:ingress envoy:ingress
juju relate istio-pilot:ingress kubeflow-volumes:ingress
juju relate kubeflow-dashboard:links kubeflow-volumes:dashboard-links
juju relate kfp-api:object-storage minio:object-storage
juju relate kfp-profile-controller:object-storage minio:object-storage
juju relate kfp-ui:object-storage minio:object-storage
juju relate mlmd:grpc envoy:grpc
juju relate mlmd:grpc kfp-metadata-writer:grpc
```

### What needs to get done

1. Create a bundle-airgap.yaml file for 1.8/stable
2. Ensure that everything is deployed as expected (ideally throught automated tests)
3. Enhance the documentation of the process

### Definition of Done

1. CKF 1.8/stable can be deployed in an airgapped environment using the provide bundle-airgap.yaml and documentation
2. Functionality is ensured through automated testing
