### ISSUE TITLE
Expose CKF in airgapped from the lxc VM to the host machine

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#897]
### Context

In airgapped testing of CKF, we are creating a lxc VM as an airgapped environment where we deploy the bundle. In order to test the Kubeflow componets, we need a way of accessing the dashboard from the host machine. 

### What needs to get done

1. Look into how to expose the lxc vm to the host
2. Add to the airgapped test scripts a step to expose the vm

### Definition of Done

After we run the airgapped test scripts, we are able to access the CKF dashboard from the host.

**Comment by NohaIhab** [comment]
We were able to access the dashboard in an airgapped env by doing the following:
* configure dex and authservice public-url to be: http://dex-auth.kubeflow.svc:5556
* create the following ingress object to forward incoming requests to the istio ingressgateway service:
  ```
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: http-ingress
    namespace: kubeflow
  spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: istio-ingressgateway-workload
              port:
                number: 80
  ```
we now need to add a step to the airgap script to create the ingress object.
